// src/constants/constants.ts

export const MAX_USERNAME_LENGTH = 10;

export const MAX_PASSWORD_LENGTH = 20;

export const MAX_ROOM_NAME_LENGTH = 10;

export const DEFAULT_TIMEOUT = 1500;

export const HTTP_STATUS = {
  OK: 200,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500
};

export const AVATAR_LIST : string[] = [
  'grinning-face',
  'grinning-face-with-big-eyes',
  'grinning-face-with-smiling-eyes',
  'beaming-face-with-smiling-eyes',
  'grinning-squinting-face',
  'grinning-face-with-sweat',
  'face-with-tears-of-joy',
  'slightly-smiling-face',
  'upside-down-face',
  'melting-face',
  'winking-face',
  'smiling-face-with-smiling-eyes',
  'smiling-face-with-halo',
  'smiling-face-with-hearts',
  'smiling-face-with-heart-eyes',
  'face-blowing-a-kiss',
  'kissing-face',
  'smiling-face',
  'kissing-face-with-closed-eyes',
  'kissing-face-with-smiling-eyes',
  'smiling-face-with-tear',
  'face-savoring-food',
  'face-with-tongue',
  'winking-face-with-tongue',
  'zany-face',
  'squinting-face-with-tongue',
  'money-mouth-face',
  'smiling-face-with-open-hands',
  'face-with-hand-over-mouth',
  'face-with-open-eyes-and-hand-over-mouth',
  'face-with-peeking-eye',
  'shushing-face',
  'thinking-face',
  'saluting-face',
  'zipper-mouth-face',
  'face-with-raised-eyebrow',
  'neutral-face',
  'expressionless-face',
  'face-without-mouth',
  'dotted-line-face',
  'face-in-clouds',
  'smirking-face',
  'unamused-face',
  'face-with-rolling-eyes',
  'grimacing-face',
  'face-exhaling',
  'lying-face',
  'relieved-face',
  'pensive-face',
  'sleepy-face',
  'drooling-face',
  'sleeping-face',
  'face-with-medical-mask',
  'face-with-thermometer',
  'face-with-head-bandage',
  'nauseated-face',
  'face-vomiting',
  'sneezing-face',
  'hot-face',
  'cold-face',
  'woozy-face',
  'face-with-crossed-out-eyes',
  'face-with-spiral-eyes',
  'cowboy-hat-face',
  'partying-face',
  'disguised-face',
  'smiling-face-with-sunglasses',
  'nerd-face',
  'face-with-monocle',
  'confused-face',
  'face-with-diagonal-mouth',
  'worried-face',
  'slightly-frowning-face',
  'frowning-face',
  'face-with-open-mouth',
  'hushed-face',
  'astonished-face',
  'flushed-face',
  'pleading-face',
  'face-holding-back-tears',
  'frowning-face-with-open-mouth',
  'anguished-face',
  'fearful-face',
  'anxious-face-with-sweat',
  'sad-but-relieved-face',
  'crying-face',
  'loudly-crying-face',
  'face-screaming-in-fear',
  'confounded-face',
  'persevering-face',
  'disappointed-face',
  'downcast-face-with-sweat',
  'weary-face',
  'tired-face',
  'yawning-face',
  'face-with-steam-from-nose',
  'angry-face',
  'face-with-symbols-on-mouth',
  'smiling-face-with-horns',
  'angry-face-with-horns',
  'clown-face',
  'person-facepalming',
  'monkey-face',
  'dog-face',
  'cat-face',
  'tiger-face',
  'horse-face',
  'cow-face',
  'pig-face',
  'mouse-face',
  'rabbit-face',
  'dragon-face',
  'new-moon-face',
  'first-quarter-moon-face',
  'last-quarter-moon-face',
  'full-moon-face',
  'sun-with-face',
  'wind-face'
]
